{% set name = "gunpowder" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gunpowder-{{ version }}.tar.gz
  sha256: 3c90cdb4b460ef04bea1285526063072b2ed3d55561bf29083323de96dd5a7b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - augment-nd >=0.1.3
    - funlib.geometry
    - h5py
    - networkx
    - numpy
    - protobuf
    - python >={{ python_min }}
    - pytorch
    - requests
    - scikit-image
    - scipy
    - tensorflow
    - tqdm
    - zarr

test:
  imports:
    - gunpowder
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gunpowder
  summary: A library to facilitate machine learning on large, multi-dimensional images..
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/funkey/gunpowder

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
